"""empty message

Revision ID: a11740a76c77
Revises: c69ffbf031ff
Create Date: 2020-05-26 13:50:11.117465

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a11740a76c77'
down_revision = 'c69ffbf031ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('playlist_song')
    op.create_unique_constraint(None, 'tune', ['title'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tune', type_='unique')
    op.create_table(
        'playlist_song',
        sa.Column(
            'id',
            sa.INTEGER(),
            autoincrement=True,
            nullable=False
        ),
        sa.Column(
            'playlist',
            sa.INTEGER(),
            autoincrement=False,
            nullable=False
        ),
        sa.Column(
            'tune',
            sa.INTEGER(),
            autoincrement=False,
            nullable=False
        ),
        sa.ForeignKeyConstraint(
                ['playlist'],
                ['playlist.id'],
                name='playlist_song_playlist_fkey'),
        sa.ForeignKeyConstraint(
            ['tune'],
            ['tune.id'],
            name='playlist_song_tune_fkey'
        ),
        sa.PrimaryKeyConstraint(
            'id',
            name='playlist_song_pkey'
        )
    )
# ### end Alembic commands ###
