"""empty message

Revision ID: c08a0423de4c
Revises: 
Create Date: 2020-05-21 22:44:40.248751

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c08a0423de4c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('playlist_songs')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('playlist_songs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('playlist', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('tune', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['playlist'], ['playlist.id'], name='playlist_songs_playlist_fkey'),
    sa.ForeignKeyConstraint(['tune'], ['tune.id'], name='playlist_songs_tune_fkey'),
    sa.PrimaryKeyConstraint('id', name='playlist_songs_pkey')
    )
    # ### end Alembic commands ###
