"""empty message

Revision ID: c69ffbf031ff
Revises: dab1d00ff850
Create Date: 2020-05-22 12:10:11.590072

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c69ffbf031ff'
down_revision = 'dab1d00ff850'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('playlist_song')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('playlist_song',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('playlist', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('tune', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['playlist'], ['playlist.id'], name='playlist_song_playlist_fkey'),
    sa.ForeignKeyConstraint(['tune'], ['tune.id'], name='playlist_song_tune_fkey'),
    sa.PrimaryKeyConstraint('id', name='playlist_song_pkey')
    )
    # ### end Alembic commands ###
